languageCode = 'en-us'
title = "ABGEO's Personal website"
copyright = 'Temuri Takalandze (ABGEO)'
disableHugoGeneratorInject = true
enableGitInfo = true
enableRobotsTXT = true
timeZone = 'Asia/Tbilisi'

[markup.goldmark.renderer]
  unsafe = true

[params]
  centerTheme = true
  readMore = 'Read More'
  newerPosts = 'Newer'
  olderPosts = 'Older'
  readOtherPosts = 'See also'
  images = ['/og-image.png']
  autoCover = true
  latestContentSize = 5

  [params.logo]
    logoText = 'visitor@abgeo.dev:~$'
    logoHomeLink = '/'
  
  [params.social]
    twitter = 'ABGEO07'
    facebook_app_id = '2095975467495214'

  [params.tools]
    facebook_pixel_id = '920682743603564'
    google_tag_manager_id = 'GTM-T6NWZ5DP'

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 3
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 4
  [[menu.main]]
    identifier = "book"
    name = "Book"
    url = "/book"
    weight = 5
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 6
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/files/cv/temuri-t-cv.pdf"
    weight = 7
    [menu.main.params]
      newTab = true
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 8

[services]
  [services.googleAnalytics]
    id = 'G-TB823JE1Y3'

[taxonomies]
  tag = 'tags'

[module]
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'
